catalog: fins_genai
image_path: /Volumes/fins_genai/unstructured_documents/pdf_examples/scanned_pdfs/images
parsed_content_table_name: fins_genai.unstructured_documents.adv_analysis_parsed_content
parsed_elements_table_name: fins_genai.unstructured_documents.adv_analysis_parsed_elements
parsed_images_elements_bbox_table_name: fins_genai.unstructured_documents.adv_analysis_prased_img_elements_bbox
parsed_pages_table_name: fins_genai.unstructured_documents.adv_analysis_parsed_pages
parsed_tables_table_name: fins_genai.unstructured_documents.adv_analysis_parsed_tables
raw_files_table_name: fins_genai.unstructured_documents.adv_analysis_raw_files
schema: unstructured_documents
source_path: /Volumes/fins_genai/unstructured_documents/pdf_examples/scanned_pdfs
volume: pdf_examples
volume_subdir: scanned_pdfs
