# Databricks notebook source
# MAGIC %md
# MAGIC # 01 — Parse + Extract with Citations (Paystubs)
# MAGIC
# MAGIC POC notebook 1 of 2 for **second-level bounding boxes** on `ai_extract`
# MAGIC entities (see `../README.md` and `second-level-bbox-recommendation.md`).
# MAGIC
# MAGIC The workflow is:
# MAGIC
# MAGIC 1. `ai_parse_document` → collect elements + saved page images (bronze).
# MAGIC 2. `ai_extract` v2.1 with **`enableCitations`** on the whole parsed
# MAGIC    document → entity value + per-field confidence + **element-level
# MAGIC    citation bboxes**.
# MAGIC 3. Flatten to the shape the visualization in NB02 expects
# MAGIC    (`image_name`, `<field>`, `<field>_extract_conf`, `<field>_citation_ids`,
# MAGIC    `citations`, `citation_pages`).
# MAGIC
# MAGIC > **Why the parsed VARIANT, not plain text, into `ai_extract`:** citation
# MAGIC > bboxes only exist because the input carries layout geometry. Plain text
# MAGIC > has no coordinates, so feeding the parsed VARIANT is what makes
# MAGIC > `citations[].bbox[].coord` populated.
# MAGIC
# MAGIC Requires **DBR 18.2+ / serverless env v3+** for `ai_extract` 2.1.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Set up environment

# COMMAND ----------

dbutils.widgets.text("catalog", "fins_genai")
dbutils.widgets.text("schema", "unstructured_documents")
dbutils.widgets.text("volume", "paystubs")
dbutils.widgets.text("volume_subdir", "")  # subfolder of PDFs under the volume; "" = volume root
dbutils.widgets.text("table_prefix", "paystub_bbox")
dbutils.widgets.dropdown("reset_data", "true", ["true", "false"])

# COMMAND ----------

catalog = dbutils.widgets.get("catalog")
schema = dbutils.widgets.get("schema")
volume = dbutils.widgets.get("volume")
volume_subdir = dbutils.widgets.get("volume_subdir").strip("/")
table_prefix = dbutils.widgets.get("table_prefix")
reset_data = dbutils.widgets.get("reset_data") == "true"

# Volume root, optionally a subdir. Page images are written to a sibling /images dir.
_vol_root = f"/Volumes/{catalog}/{schema}/{volume}"
source_path = f"{_vol_root}/{volume_subdir}" if volume_subdir else _vol_root
image_path = f"{source_path}/images"
crops_path = f"{source_path}/crops"
dbutils.fs.mkdirs(image_path)
dbutils.fs.mkdirs(crops_path)

pipeline_config = {
    "source_path":    source_path,
    "image_path":     image_path,
    "crops_path":     crops_path,
    "bronze_table":    f"{catalog}.{schema}.{table_prefix}_bronze_parsed_docs",
    "extracted_table": f"{catalog}.{schema}.{table_prefix}_extracted",
    "flat_table":      f"{catalog}.{schema}.{table_prefix}_extracted_flat",
}
print(pipeline_config)

# COMMAND ----------

# MAGIC %md
# MAGIC ### Save config to yaml — NB02 reads it back

# COMMAND ----------

import yaml

with open("config.yaml", "w") as f:
    yaml.dump(
        {
            "catalog": catalog,
            "schema": schema,
            "volume": volume,
            "volume_subdir": volume_subdir,
            "table_prefix": table_prefix,
            **pipeline_config,
        },
        f,
    )

# COMMAND ----------

dbutils.fs.rm(pipeline_config["image_path"], recurse=True)

# COMMAND ----------

# DBTITLE 1,Reset tables and images
if reset_data:
    print("Dropping existing POC tables ...")
    for key in ("bronze_table", "extracted_table", "flat_table"):
        spark.sql(f"DROP TABLE IF EXISTS {pipeline_config[key]}")

    # Drop OCR tokens table (generated by NB02 Stage 1) to avoid stale joins
    ocr_table = f"{catalog}.{schema}.{table_prefix}_ocr_tokens"
    print(f"Dropping OCR tokens table: {ocr_table} ...")
    spark.sql(f"DROP TABLE IF EXISTS {ocr_table}")

    # Delete page images so ai_parse_document regenerates them
    print(f"Removing page images under {pipeline_config['image_path']} ...")
    print(f"Removing cropped images under {pipeline_config['crops_path']} ...")

    try:
        dbutils.fs.rm(pipeline_config["image_path"], recurse=True)
        dbutils.fs.rm(pipeline_config["crops_path"], recurse=True)

        print("  Done — images cleared.")
    except Exception as e:
        print(f"  (skipped — {e})")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Parse with `ai_parse_document` (bronze)
# MAGIC
# MAGIC `imageOutputPath` is set so each page is rasterized to an image whose path
# MAGIC is recorded at `document.pages[].image_uri`. NB02 crops those images.

# COMMAND ----------

from pyspark.sql.functions import expr, current_timestamp, col

raw = (
    spark.read.format("binaryFile")
    .option("recursiveFileLookup", "false")
    .option("pathGlobFilter", "*.pdf")
    .load(pipeline_config["source_path"])
    .filter(~col("path").contains("/images/"))
)

parsed = (
    raw.withColumn(
        "parsed",
        expr(
            "ai_parse_document(content, "
            "map('version', '2.0', "
            f"'imageOutputPath', '{pipeline_config['image_path']}', "
            "'descriptionElementTypes', '*'))"
        ),
    )
    .select("path", "parsed")
    .withColumn("ingested_at", current_timestamp())
)

(
    parsed.write.format("delta")
    .mode("overwrite")
    .option("overwriteSchema", "true")
    .saveAsTable(pipeline_config["bronze_table"])
)

display(spark.sql(f"""
SELECT
  path,
  parsed:metadata:file_metadata:file_name::string AS file_name,
  parsed:metadata:version::string                 AS schema_version,
  size(variant_get(parsed, '$.document.pages',    'array<variant>')) AS page_count,
  size(variant_get(parsed, '$.document.elements', 'array<variant>')) AS element_count,
  size(variant_get(parsed, '$.error_status',      'array<variant>')) AS error_count
FROM {pipeline_config['bronze_table']}
ORDER BY file_name
"""))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Check bbox structure — native sub-element geometry or not?
# MAGIC
# MAGIC Inspect the full schema and one raw element below. Look under each element
# MAGIC for anything beyond `bbox[0].coord` (e.g. `bbox` with > 1 entry, or a nested
# MAGIC `lines`/`words`/`spans` array with their own `coord`).

# COMMAND ----------

# Full nested schema of the parsed VARIANT.
spark.sql(
    f"SELECT schema_of_variant_agg(parsed) AS parsed_schema FROM {pipeline_config['bronze_table']}"
).show(truncate=False)

# COMMAND ----------

import json

df = spark.sql(f"""
SELECT to_json(
  parsed
) AS parsed_json
FROM {pipeline_config['bronze_table']}
LIMIT 1
""")

parsed_json = df.collect()[0]["parsed_json"]
print(json.dumps(json.loads(parsed_json), indent=2))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Extract paystub fields with citations
# MAGIC
# MAGIC One `ai_extract` over the whole parsed document (no page split, no class
# MAGIC routing). The schema mixes **paragraph-text** fields (employer/employee
# MAGIC name) and **table-cell** fields (the earnings/deductions amounts) — the two
# MAGIC localization cases the POC needs to cover.

# COMMAND ----------

# DBTITLE 1,Cell 14
EXTRACT_INPUT = "parsed"  # whole parsed VARIANT → citations carry element bboxes

PAYSTUB_SCHEMA = """{
  "employee_name": {
    "type": "string",
    "description": "The employee's full name printed on the paystub."
  },
  "employer_name": {
    "type": "string",
    "description": "The employer / company legal name printed on the paystub."
  },
  "social_security_number": {
    "type": "string",
    "description": "The employee's Social Security Number (taxpayer identifier) as printed."
  },
  "taxable_marital_status": {
    "type": "string",
    "description": "The taxable marital status (e.g. Married | Unmarried | Separated | Single)."
  },
  "borrower_employee_address": {
    "type": "object",
    "description": "Employee address information.",
    "properties": {
      "address_line": {
        "type": "string",
        "description": "The street address line in the employee address block."
      },
      "city_name": {
        "type": "string",
        "description": "The city in the employee address block."
      },
      "state_code": {
        "type": "string",
        "description": "The state code in the employee address block."
      },
      "zip_code": {
        "type": "string",
        "description": "The ZIP / postal code in the employee address block."
      }
    }
  },
  "borrower_employer_address": {
    "type": "object",
    "description": "Employer address information.",
    "properties": {
      "address_line": {
        "type": "string",
        "description": "The street address line in the employer address block."
      },
      "city_name": {
        "type": "string",
        "description": "The city in the employer address block."
      },
      "state_code": {
        "type": "string",
        "description": "The state code in the employer address block."
      },
      "zip_code": {
        "type": "string",
        "description": "The ZIP / postal code in the employer address block."
      }
    }
  },
  "hire_date": {
    "type": "string",
    "description": "The employee hire date as printed."
  },
  "ets_date": {
    "type": "string",
    "description": "The ETS (term-of-service expiration) date as printed, if present."
  },
  "pay_date": {
    "type": "string",
    "description": "The paycheck date as printed."
  },
  "period_start_date": {
    "type": "string",
    "description": "The pay-period start date as printed."
  },
  "period_end_date": {
    "type": "string",
    "description": "The pay-period end date as printed."
  },
  "payment_frequency": {
    "type": "string",
    "description": "The payment frequency type (e.g. Weekly | Biweekly | Monthly)."
  },
  "income_source_type": {
    "type": "string",
    "description": "Whether the employee is paid Hourly or Salaried."
  },
  "gross": {
    "type": "object",
    "description": "Gross pay amounts.",
    "properties": {
      "current_amount": {
        "type": "number",
        "description": "The gross pay for the current pay period."
      },
      "year_to_date_amount": {
        "type": "number",
        "description": "The year-to-date gross pay."
      }
    }
  },
  "net_pay": {
    "type": "object",
    "description": "Net pay amounts.",
    "properties": {
      "current_amount": {
        "type": "number",
        "description": "The net pay for the current pay period."
      },
      "year_to_date_amount": {
        "type": "number",
        "description": "The year-to-date net pay."
      }
    }
  },
  "adjustments_gross_income": {
    "type": "object",
    "description": "Adjustments to gross income amounts.",
    "properties": {
      "current_amount": {
        "type": "number",
        "description": "The current-period adjustments gross income amount."
      },
      "year_to_date_amount": {
        "type": "number",
        "description": "The year-to-date adjustments gross income amount."
      }
    }
  },
  "income_item": {
    "type": "array",
    "description": "Repeating earning/income rows on the paystub; one object per printed row.",
    "items": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "description": "The earning item description (e.g. Regular, Overtime)."
        },
        "period_hours": {
          "type": "number",
          "description": "The hours for this earning item this period."
        },
        "rate": {
          "type": "number",
          "description": "The pay rate for this earning item."
        },
        "current_amount": {
          "type": "number",
          "description": "The current-period amount for this earning item."
        },
        "year_to_date_amount": {
          "type": "number",
          "description": "The year-to-date amount for this earning item."
        }
      }
    }
  },
  "deduction_item": {
    "type": "array",
    "description": "Repeating deduction rows on the paystub; one object per printed row.",
    "items": {
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "description": "The deduction item description (e.g. Federal Tax, Medicare)."
        },
        "period_amount": {
          "type": "number",
          "description": "The current-period amount for this deduction item."
        },
        "year_to_date_amount": {
          "type": "number",
          "description": "The year-to-date amount for this deduction item."
        }
      }
    }
  }
}"""

INSTRUCTIONS = (
    "The uploaded documents are US consumer paystubs (monthly or weekly). "
    "Extract the named fields. Use the exact text as printed; do not reformat "
    "dates or amounts. Leave a field blank if it is not present. income_item, "
    "deduction_item are repeating rows: emit one object per printed row, "
    "including zero-activity rows that are actually present."
)

# Field specifications: (flat_column_name, variant_response_path, sql_type)
# variant_response_path is the dotted path under $.response.{path}.value
FIELD_SPECS = [
    # Top-level scalars
    ("employee_name",                           "employee_name",                           "string"),
    ("employer_name",                           "employer_name",                           "string"),
    ("social_security_number",                  "social_security_number",                  "string"),
    ("taxable_marital_status",                  "taxable_marital_status",                  "string"),
    # Employee address (nested object)
    ("borrower_employee_address__address_line", "borrower_employee_address.address_line",  "string"),
    ("borrower_employee_address__city_name",    "borrower_employee_address.city_name",     "string"),
    ("borrower_employee_address__state_code",   "borrower_employee_address.state_code",    "string"),
    ("borrower_employee_address__zip_code",     "borrower_employee_address.zip_code",      "string"),
    # Employer address (nested object)
    ("borrower_employer_address__address_line", "borrower_employer_address.address_line",  "string"),
    ("borrower_employer_address__city_name",    "borrower_employer_address.city_name",     "string"),
    ("borrower_employer_address__state_code",   "borrower_employer_address.state_code",    "string"),
    ("borrower_employer_address__zip_code",     "borrower_employer_address.zip_code",      "string"),
    # Dates
    ("hire_date",                               "hire_date",                               "string"),
    ("ets_date",                                "ets_date",                                "string"),
    ("pay_date",                                "pay_date",                                "string"),
    ("period_start_date",                       "period_start_date",                       "string"),
    ("period_end_date",                         "period_end_date",                         "string"),
    # Pay metadata
    ("payment_frequency",                       "payment_frequency",                       "string"),
    ("income_source_type",                      "income_source_type",                      "string"),
    # Gross (nested object)
    ("gross__current_amount",                   "gross.current_amount",                    "double"),
    ("gross__year_to_date_amount",              "gross.year_to_date_amount",               "double"),
    # Net pay (nested object)
    ("net_pay__current_amount",                 "net_pay.current_amount",                  "double"),
    ("net_pay__year_to_date_amount",            "net_pay.year_to_date_amount",             "double"),
    # Adjustments (nested object)
    ("adjustments_gross_income__current_amount",         "adjustments_gross_income.current_amount",         "double"),
    ("adjustments_gross_income__year_to_date_amount",    "adjustments_gross_income.year_to_date_amount",    "double"),
]

# Derived convenience lists for downstream cells
EXTRACT_FIELDS = [col_name for col_name, _, _ in FIELD_SPECS]
NUMBER_FIELDS = {col_name for col_name, _, sql_type in FIELD_SPECS if sql_type == "double"}

# Array fields — extracted as VARIANT for NB02 to unpack per-element sub-fields
ARRAY_FIELDS = ["income_item", "deduction_item"]

# Sub-field definitions for array fields (used by NB02 localization)
ARRAY_SUB_FIELDS = {
    "income_item": [
        ("description",      "string"),
        ("period_hours",     "double"),
        ("rate",             "double"),
        ("current_amount",   "double"),
        ("year_to_date_amount", "double"),
    ],
    "deduction_item": [
        ("description",      "string"),
        ("period_amount",    "double"),
        ("year_to_date_amount", "double"),
    ],
}

# COMMAND ----------

schema_sql = PAYSTUB_SCHEMA.replace("'", "''")
instr_sql = INSTRUCTIONS.replace("'", "''")

spark.sql(f"""
CREATE OR REPLACE TABLE {pipeline_config['extracted_table']} AS
SELECT
  path,
  -- first page image as a row-level fallback; citation_pages carries per-page uris
  variant_get(parsed, '$.document.pages[0].image_uri', 'string') AS image_uri,
  -- NB02 joins citation bboxes back to parsed elements to recover source text.
  variant_get(parsed, '$.document.elements', 'variant') AS parsed_elements,
  ai_extract(
    {EXTRACT_INPUT},
    '{schema_sql}',
    options => map(
      'version',                '2.1',
      'enableCitations',        'true',
      'enableConfidenceScores', 'true',
      'instructions',           '{instr_sql}'
    )
  ) AS paystub_extracted
FROM {pipeline_config['bronze_table']}
""")

display(spark.table(pipeline_config["extracted_table"]))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Validate — citation shape
# MAGIC
# MAGIC Confirm where citations exist in the `ai_extract` VARIANT.
# MAGIC
# MAGIC Eyeball the JSON below and confirm these paths before trusting the flatten
# MAGIC cell that follows:
# MAGIC
# MAGIC - field value:   `$.response.<field>.value`
# MAGIC - field conf:    `$.response.<field>.confidence_score`
# MAGIC - field cites:   `$.response.<field>.citation_ids`  (array of citation ids)
# MAGIC - citations:     `$.metadata.citations` → `[{id, bbox:[{coord,page_id}]}]`
# MAGIC - citation pages:`$.metadata.pages`     → `[{id, image_uri}]`
# MAGIC
# MAGIC For `ai_parse_document` VARIANT inputs, bbox citations do **not** carry a raw
# MAGIC text/snippet field. NB02 resolves the citation bbox back to
# MAGIC `parsed.document.elements` and derives the raw match target from that element
# MAGIC text.

# COMMAND ----------

display(spark.sql(f"""
SELECT to_json(paystub_extracted) AS extracted_json
FROM {pipeline_config['extracted_table']}
LIMIT 1
"""))

# COMMAND ----------

import json

df = spark.sql(f"""
SELECT to_json(paystub_extracted) AS extracted_json
FROM {pipeline_config['extracted_table']}
LIMIT 1
""")

extracted_json = df.collect()[0]["extracted_json"]
print(json.dumps(json.loads(extracted_json), indent=2))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Flatten to the visualization shape
# MAGIC
# MAGIC Builds the columns NB02's `CitationRenderer` consumes. **Paths assumed from
# MAGIC the documented v2.1 shape — verify against the JSON above and edit if
# MAGIC needed.** `image_name` keys the per-document selector in NB02.

# COMMAND ----------

# DBTITLE 1,Cell 20
RESPONSE_ROOT = "response"

select_clauses = [
    "path",
    "image_uri",
    "parsed_elements",
    # image_name = page-image basename if present, else the pdf basename
    "COALESCE(element_at(split(image_uri, '/'), -1), "
    "element_at(split(path, '/'), -1)) AS image_name",
]

# Scalar fields — use FIELD_SPECS to map flat column names to nested VARIANT paths
for col_name, variant_path, sql_type in FIELD_SPECS:
    select_clauses.append(
        f"variant_get(paystub_extracted, '$.{RESPONSE_ROOT}.{variant_path}.value', '{sql_type}') AS {col_name}"
    )
    select_clauses.append(
        f"variant_get(paystub_extracted, '$.{RESPONSE_ROOT}.{variant_path}.confidence_score', 'double') AS {col_name}_extract_conf"
    )
    select_clauses.append(
        f"variant_get(paystub_extracted, '$.{RESPONSE_ROOT}.{variant_path}.citation_ids', 'array<int>') AS {col_name}_citation_ids"
    )

# Array fields — stored directly at $.response.<array_field> (no .value wrapper).
# Per-element sub-field citations live inside each element, not at the array level.
for af in ARRAY_FIELDS:
    select_clauses.append(f"variant_get(paystub_extracted, '$.{RESPONSE_ROOT}.{af}', 'variant') AS {af}")

# Keep the two citation VARIANTs whole for NB02.
select_clauses.append("variant_get(paystub_extracted, '$.metadata.citations', 'variant') AS citations")
select_clauses.append("variant_get(paystub_extracted, '$.metadata.pages', 'variant') AS citation_pages")

flat_sql = f"""
CREATE OR REPLACE TABLE {pipeline_config['flat_table']} AS
SELECT
  {','.join(select_clauses)}
FROM {pipeline_config['extracted_table']}
"""
spark.sql(flat_sql)
display(spark.table(pipeline_config["flat_table"]))

# COMMAND ----------

# MAGIC %md
# MAGIC ## Verify

# COMMAND ----------

# Fields that actually got a value + at least one citation.
display(spark.sql(f"""
SELECT
  image_name,
  {', '.join([f"size({f}_citation_ids) AS {f}_ncites" for f in EXTRACT_FIELDS])}
FROM {pipeline_config['flat_table']}
ORDER BY image_name
LIMIT 20
"""))

# COMMAND ----------

df = spark.table(pipeline_config["bronze_table"]).select(
    "path",
    "parsed"
).withColumn(
    "page_count",
    expr("size(variant_get(parsed, '$.document.pages', 'array<variant>'))")
)

display(df.agg({"page_count": "sum"}).withColumnRenamed("sum(page_count)", "total_page_count"))

# COMMAND ----------

print(f'Total page images: {len(dbutils.fs.ls("/Volumes/fins_genai/unstructured_documents/paystubs/images/"))}')